theme: minima

title: Joel Tan
author:
  name: Tan Zu Wei Joel
  email: joeltanzu@gmail.com

minima:
  skin: dark
  date_format: "%-d %b, %Y"

  # generate social links in footer
  social_links:
    github:  joeltanzu
    linkedin: joeltanzu

google_analytics: UA-168909721-1

header_pages:
  - projects.md
  - cv.md
  - blog.md

plugins:
 - jekyll-seo-tag 